name: GitHub Actions


on:
  release:
    types: [published, edited]


jobs:
  Explore-GitHub-Actions:
  
    runs-on: ubuntu-latest
    
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Setting up .NET Core SDK v3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
    
      - name: Running tests
        run: dotnet test
